version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    deploy:
          resources:
              limits:
                cpus: '0.50'
                memory: 2000M
              reservations:
                cpus: '0.25'
                memory: 512M
    depends_on:
      - eureka-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
  gcc:
    build: ./gcc
    deploy:
          resources:
              limits:
                cpus: '0.50'
                memory: 2000M
              reservations:
                cpus: '0.25'
                memory: 512M
    depends_on:
      - eureka-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
  
  gcc2:
    build: ./gcc
    deploy:
          resources:
              limits:
                cpus: '0.50'
                memory: 2000M
              reservations:
                cpus: '0.25'
                memory: 512M
    depends_on:
      - eureka-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
  
  gcc3:
    build: ./gcc
    deploy:
          resources:
              limits:
                cpus: '0.50'
                memory: 2000M
              reservations:
                cpus: '0.25'
                memory: 512M
    depends_on:
      - eureka-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
  
  py:
    build: ./py
    deploy:
          resources:
              limits:
                cpus: '0.50'
                memory: 2000M
              reservations:
                cpus: '0.25'
                memory: 512M
    depends_on:
      - eureka-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
  
  java:
    build: ./java
    deploy:
          resources:
              limits:
                cpus: '0.50'
                memory: 2000M
              reservations:
                cpus: '0.25'
                memory: 512M
    depends_on:
      - eureka-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
  eureka-server:
    build: ./eureka
    ports:
      - "8761:8761"
    environment:
      eureka.instance.hostname: eureka-server
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka  
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: