version: "3.9"
services:
  backend:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/app
  redis1:
    image: "redis:alpine"
  redis2:
    image: "redis:alpine"
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
  mongodb: